// Auto-generated by scripts/generate-terminal-content.mjs
// Do not edit manually - run "pnpm generate" to regenerate

import pkg from "../../../../package.json";

export const version = pkg.version;

// Command outputs
export const CMD_ABOUT = `just-bash v${pkg.version}
A TypeScript bash interpreter with in-memory filesystem.
Designed for AI agents needing a secure, sandboxed environment.

Custom commands:
  about       About just-bash
  install     Installation instructions
  github      GitHub repository

Or try any bash command: ls, cat, echo, grep, awk, jq, sed, etc.
Type 'help' for a list of all built-in commands.
`;

export const CMD_INSTALL = `npm install just-bash

Usage:
  import { Bash } from "just-bash";
  const bash = new Bash();
  const result = await bash.exec("echo hello");
`;

export const CMD_GITHUB = "https://github.com/vercel-labs/just-bash\n";

// File contents (generated from repo)
export const FILE_README = `# just-bash

A simulated bash environment with an in-memory virtual filesystem, written in TypeScript.

Designed for AI agents that need a secure, sandboxed bash environment.

Supports optional network access via \`curl\` with secure-by-default URL filtering.

**Note**: This is beta software. Use at your own risk and please provide feedback.

## Table of Contents

- [Security model](#security-model)
- [Installation](#installation)
- [Usage](#usage)
  - [Basic API](#basic-api)
  - [Configuration](#configuration)
  - [Custom Commands](#custom-commands)
  - [Filesystem Options](#filesystem-options)
  - [AI SDK Tool](#ai-sdk-tool)
  - [Vercel Sandbox Compatible API](#vercel-sandbox-compatible-api)
  - [CLI Binary](#cli-binary)
  - [Interactive Shell](#interactive-shell)
- [Supported Commands](#supported-commands)
- [Shell Features](#shell-features)
- [Default Layout](#default-layout)
- [Network Access](#network-access)
- [Execution Protection](#execution-protection)
- [Development](#development)

## Security model

- The shell only has access to the provided file system.
- Execution is protected against infinite loops or recursion. However, Bash is not fully robust against DOS from input. If you need to be robust against this, use process isolation at the OS level.
- Binaries or even WASM are inherently unsupported (Use [Vercel Sandbox](https://vercel.com/docs/vercel-sandbox) or a similar product if a full VM is needed).
- There is no network access by default.
- Network access can be enabled, but requests are checked against URL prefix allow-lists and HTTP-method allow-lists. See [network access](#network-access) for details

## Installation

\`\`\`bash
npm install just-bash
\`\`\`

## Usage

### Basic API

\`\`\`typescript
import { Bash } from "just-bash";

const env = new Bash();
await env.exec('echo "Hello" > greeting.txt');
const result = await env.exec("cat greeting.txt");
console.log(result.stdout); // "Hello\\n"
console.log(result.exitCode); // 0
console.log(result.env); // Final environment after execution
\`\`\`

Each \`exec()\` is isolated—env vars, functions, and cwd don't persist across calls (filesystem does).

### Configuration

\`\`\`typescript
const env = new Bash({
  files: { "/data/file.txt": "content" }, // Initial files
  env: { MY_VAR: "value" }, // Initial environment
  cwd: "/app", // Starting directory (default: /home/user)
  executionLimits: { maxCallDepth: 50 }, // See "Execution Protection"
});

// Per-exec overrides
await env.exec("echo $TEMP", { env: { TEMP: "value" }, cwd: "/tmp" });
\`\`\`

### Custom Commands

Extend just-bash with your own TypeScript commands using \`defineCommand\`:

\`\`\`typescript
import { Bash, defineCommand } from "just-bash";

const hello = defineCommand("hello", async (args, ctx) => {
  const name = args[0] || "world";
  return { stdout: \`Hello, \${name}!\\n\`, stderr: "", exitCode: 0 };
});

const upper = defineCommand("upper", async (args, ctx) => {
  return { stdout: ctx.stdin.toUpperCase(), stderr: "", exitCode: 0 };
});

const bash = new Bash({ customCommands: [hello, upper] });

await bash.exec("hello Alice"); // "Hello, Alice!\\n"
await bash.exec("echo 'test' | upper"); // "TEST\\n"
\`\`\`

Custom commands receive the full \`CommandContext\` with access to \`fs\`, \`cwd\`, \`env\`, \`stdin\`, and \`exec\` for running subcommands.

### Filesystem Options

Four filesystem implementations are available:

**InMemoryFs** (default) - Pure in-memory filesystem, no disk access:

\`\`\`typescript
import { Bash } from "just-bash";
const env = new Bash(); // Uses InMemoryFs by default
\`\`\`

**OverlayFs** - Copy-on-write over a real directory. Reads come from disk, writes stay in memory:

\`\`\`typescript
import { Bash } from "just-bash";
import { OverlayFs } from "just-bash/fs/overlay-fs";

const overlay = new OverlayFs({ root: "/path/to/project" });
const env = new Bash({ fs: overlay, cwd: overlay.getMountPoint() });

await env.exec("cat package.json"); // reads from disk
await env.exec('echo "modified" > package.json'); // stays in memory
\`\`\`

**ReadWriteFs** - Direct read-write access to a real directory. Use this if you want the agent to be agle to write to your disk:

\`\`\`typescript
import { Bash } from "just-bash";
import { ReadWriteFs } from "just-bash/fs/read-write-fs";

const rwfs = new ReadWriteFs({ root: "/path/to/sandbox" });
const env = new Bash({ fs: rwfs });

await env.exec('echo "hello" > file.txt'); // writes to real filesystem
\`\`\`

**MountableFs** - Mount multiple filesystems at different paths. Combines read-only and read-write filesystems into a unified namespace:

\`\`\`typescript
import { Bash, MountableFs, InMemoryFs } from "just-bash";
import { OverlayFs } from "just-bash/fs/overlay-fs";
import { ReadWriteFs } from "just-bash/fs/read-write-fs";

const fs = new MountableFs({ base: new InMemoryFs() });

// Mount read-only knowledge base
fs.mount("/mnt/knowledge", new OverlayFs({ root: "/path/to/knowledge", readOnly: true }));

// Mount read-write workspace
fs.mount("/home/agent", new ReadWriteFs({ root: "/path/to/workspace" }));

const bash = new Bash({ fs, cwd: "/home/agent" });

await bash.exec("ls /mnt/knowledge"); // reads from knowledge base
await bash.exec("cp /mnt/knowledge/doc.txt ./"); // cross-mount copy
await bash.exec('echo "notes" > notes.txt'); // writes to workspace
\`\`\`

You can also configure mounts in the constructor:

\`\`\`typescript
import { MountableFs, InMemoryFs } from "just-bash";
import { OverlayFs } from "just-bash/fs/overlay-fs";
import { ReadWriteFs } from "just-bash/fs/read-write-fs";

const fs = new MountableFs({
  base: new InMemoryFs(),
  mounts: [
    { mountPoint: "/data", filesystem: new OverlayFs({ root: "/shared/data" }) },
    { mountPoint: "/workspace", filesystem: new ReadWriteFs({ root: "/tmp/work" }) },
  ],
});
\`\`\`

### AI SDK Tool

For AI agents, use [\`bash-tool\`](https://github.com/vercel-labs/bash-tool) which is optimized for just-bash and provides a ready-to-use [AI SDK](https://ai-sdk.dev/) tool:

\`\`\`bash
npm install bash-tool
\`\`\`

\`\`\`typescript
import { createBashTool } from "bash-tool";
import { generateText } from "ai";

const bashTool = createBashTool({
  files: { "/data/users.json": '[{"name": "Alice"}, {"name": "Bob"}]' },
});

const result = await generateText({
  model: "anthropic/claude-sonnet-4",
  tools: { bash: bashTool },
  prompt: "Count the users in /data/users.json",
});
\`\`\`

See the [bash-tool documentation](https://github.com/vercel-labs/bash-tool) for more details and examples.

### Vercel Sandbox Compatible API

Bash provides a \`Sandbox\` class that's API-compatible with [\`@vercel/sandbox\`](https://vercel.com/docs/vercel-sandbox), making it easy to swap implementations. You can start with Bash and switch to a real sandbox when you need the power of a full VM (e.g. to run node, python, or custom binaries).

\`\`\`typescript
import { Sandbox } from "just-bash";

// Create a sandbox instance
const sandbox = await Sandbox.create({ cwd: "/app" });

// Write files to the virtual filesystem
await sandbox.writeFiles({
  "/app/script.sh": 'echo "Hello World"',
  "/app/data.json": '{"key": "value"}',
});

// Run commands and get results
const cmd = await sandbox.runCommand("bash /app/script.sh");
const output = await cmd.stdout(); // "Hello World\\n"
const exitCode = (await cmd.wait()).exitCode; // 0

// Read files back
const content = await sandbox.readFile("/app/data.json");

// Create directories
await sandbox.mkDir("/app/logs", { recursive: true });

// Clean up (no-op for Bash, but API-compatible)
await sandbox.stop();
\`\`\`

### CLI Binary

After installing globally (\`npm install -g just-bash\`), use the \`just-bash\` command as a secure alternative to \`bash\` for AI agents:

\`\`\`bash
# Execute inline script
just-bash -c 'ls -la && cat package.json | head -5'

# Execute with specific project root
just-bash -c 'grep -r "TODO" src/' --root /path/to/project

# Pipe script from stdin
echo 'find . -name "*.ts" | wc -l' | just-bash

# Execute a script file
just-bash ./scripts/deploy.sh

# Get JSON output for programmatic use
just-bash -c 'echo hello' --json
# Output: {"stdout":"hello\\n","stderr":"","exitCode":0}
\`\`\`

The CLI uses OverlayFS - reads come from the real filesystem, but all writes stay in memory and are discarded after execution. The project root is mounted at \`/home/user/project\`.

Options:

- \`-c <script>\` - Execute script from argument
- \`--root <path>\` - Root directory (default: current directory)
- \`--cwd <path>\` - Working directory in sandbox
- \`-e, --errexit\` - Exit on first error
- \`--json\` - Output as JSON

### Interactive Shell

\`\`\`bash
pnpm shell
\`\`\`

The interactive shell has full internet access enabled by default, allowing you to use \`curl\` to fetch data from any URL. Use \`--no-network\` to disable this:

\`\`\`bash
pnpm shell --no-network
\`\`\`

## Supported Commands

### File Operations

\`cat\`, \`cp\`, \`file\`, \`ln\`, \`ls\`, \`mkdir\`, \`mv\`, \`readlink\`, \`rm\`, \`rmdir\`, \`split\`, \`stat\`, \`touch\`, \`tree\`

### Text Processing

\`awk\`, \`base64\`, \`column\`, \`comm\`, \`cut\`, \`diff\`, \`expand\`, \`fold\`, \`grep\` (+ \`egrep\`, \`fgrep\`), \`head\`, \`join\`, \`md5sum\`, \`nl\`, \`od\`, \`paste\`, \`printf\`, \`rev\`, \`rg\`, \`sed\`, \`sha1sum\`, \`sha256sum\`, \`sort\`, \`strings\`, \`tac\`, \`tail\`, \`tr\`, \`unexpand\`, \`uniq\`, \`wc\`, \`xargs\`

### Data Processing

\`jq\` (JSON), \`python3\`/\`python\` (Python via Pyodide), \`sqlite3\` (SQLite), \`xan\` (CSV), \`yq\` (YAML/XML/TOML/CSV)

### Compression & Archives

\`gzip\` (+ \`gunzip\`, \`zcat\`), \`tar\`

### Navigation & Environment

\`basename\`, \`cd\`, \`dirname\`, \`du\`, \`echo\`, \`env\`, \`export\`, \`find\`, \`hostname\`, \`printenv\`, \`pwd\`, \`tee\`

### Shell Utilities

\`alias\`, \`bash\`, \`chmod\`, \`clear\`, \`date\`, \`expr\`, \`false\`, \`help\`, \`history\`, \`seq\`, \`sh\`, \`sleep\`, \`time\`, \`timeout\`, \`true\`, \`unalias\`, \`which\`, \`whoami\`

### Network Commands

\`curl\`, \`html-to-markdown\`

All commands support \`--help\` for usage information.

## Shell Features

- **Pipes**: \`cmd1 | cmd2\`
- **Redirections**: \`>\`, \`>>\`, \`2>\`, \`2>&1\`, \`<\`
- **Command chaining**: \`&&\`, \`||\`, \`;\`
- **Variables**: \`$VAR\`, \`\${VAR}\`, \`\${VAR:-default}\`
- **Positional parameters**: \`$1\`, \`$2\`, \`$@\`, \`$#\`
- **Glob patterns**: \`*\`, \`?\`, \`[...]\`
- **If statements**: \`if COND; then CMD; elif COND; then CMD; else CMD; fi\`
- **Functions**: \`function name { ... }\` or \`name() { ... }\`
- **Local variables**: \`local VAR=value\`
- **Loops**: \`for\`, \`while\`, \`until\`
- **Symbolic links**: \`ln -s target link\`
- **Hard links**: \`ln target link\`

## Default Layout

When created without options, Bash provides a Unix-like directory structure:

- \`/home/user\` - Default working directory (and \`$HOME\`)
- \`/bin\` - Contains stubs for all built-in commands
- \`/usr/bin\` - Additional binary directory
- \`/tmp\` - Temporary files directory

Commands can be invoked by path (e.g., \`/bin/ls\`) or by name.

## Network Access

Network access (and the \`curl\` command) is disabled by default for security. To enable it, configure the \`network\` option:

\`\`\`typescript
// Allow specific URLs with GET/HEAD only (safest)
const env = new Bash({
  network: {
    allowedUrlPrefixes: [
      "https://api.github.com/repos/myorg/",
      "https://api.example.com",
    ],
  },
});

// Allow specific URLs with additional methods
const env = new Bash({
  network: {
    allowedUrlPrefixes: ["https://api.example.com"],
    allowedMethods: ["GET", "HEAD", "POST"], // Default: ["GET", "HEAD"]
  },
});

// Allow all URLs and methods (use with caution)
const env = new Bash({
  network: { dangerouslyAllowFullInternetAccess: true },
});
\`\`\`

**Note:** The \`curl\` command only exists when network is configured. Without network configuration, \`curl\` returns "command not found".

## SQLite Support

The \`sqlite3\` command uses sql.js (WASM-based SQLite) which is fully sandboxed and cannot access the real filesystem:

\`\`\`typescript
const env = new Bash();

// Query in-memory database
await env.exec('sqlite3 :memory: "SELECT 1 + 1"');

// Query file-based database
await env.exec('sqlite3 data.db "SELECT * FROM users"');
\`\`\`

**Note:** SQLite is not available in browser environments. Queries run in a worker thread with a configurable timeout (default: 5 seconds) to prevent runaway queries from blocking execution.

### Allow-List Security

The allow-list enforces:

- **Origin matching**: URLs must match the exact origin (scheme + host + port)
- **Path prefix**: Only paths starting with the specified prefix are allowed
- **HTTP method restrictions**: Only GET and HEAD by default (configure \`allowedMethods\` for more)
- **Redirect protection**: Redirects to non-allowed URLs are blocked

### Using curl

\`\`\`bash
# Fetch and process data
curl -s https://api.example.com/data | grep pattern

# Download and convert HTML to Markdown
curl -s https://example.com | html-to-markdown

# POST JSON data
curl -X POST -H "Content-Type: application/json" \\
  -d '{"key":"value"}' https://api.example.com/endpoint
\`\`\`

## Execution Protection

Bash protects against infinite loops and deep recursion with configurable limits:

\`\`\`typescript
const env = new Bash({
  executionLimits: {
    maxCallDepth: 100, // Max function recursion depth
    maxCommandCount: 10000, // Max total commands executed
    maxLoopIterations: 10000, // Max iterations per loop
    maxAwkIterations: 10000, // Max iterations in awk programs
    maxSedIterations: 10000, // Max iterations in sed scripts
  },
});
\`\`\`

All limits have sensible defaults. Error messages include hints on which limit to increase. Feel free to increase if your scripts intentionally go beyond them.

## Development

\`\`\`bash
pnpm test        # Run tests in watch mode
pnpm test:run    # Run tests once
pnpm typecheck   # Type check without emitting
pnpm build       # Build TypeScript
pnpm shell       # Run interactive shell
\`\`\`

## AI Agent Instructions

For AI agents, we recommend using [\`bash-tool\`](https://github.com/vercel-labs/bash-tool) which is optimized for just-bash and provides additional guidance in its \`AGENTS.md\`:

\`\`\`bash
cat node_modules/bash-tool/dist/AGENTS.md
\`\`\`

## License

Apache-2.0
`;

export const FILE_LICENSE = `                                 Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION

1.  Definitions.

    "License" shall mean the terms and conditions for use, reproduction,
    and distribution as defined by Sections 1 through 9 of this document.

    "Licensor" shall mean the copyright owner or entity authorized by
    the copyright owner that is granting the License.

    "Legal Entity" shall mean the union of the acting entity and all
    other entities that control, are controlled by, or are under common
    control with that entity. For the purposes of this definition,
    "control" means (i) the power, direct or indirect, to cause the
    direction or management of such entity, whether by contract or
    otherwise, or (ii) ownership of fifty percent (50%) or more of the
    outstanding shares, or (iii) beneficial ownership of such entity.

    "You" (or "Your") shall mean an individual or Legal Entity
    exercising permissions granted by this License.

    "Source" form shall mean the preferred form for making modifications,
    including but not limited to software source code, documentation
    source, and configuration files.

    "Object" form shall mean any form resulting from mechanical
    transformation or translation of a Source form, including but
    not limited to compiled object code, generated documentation,
    and conversions to other media types.

    "Work" shall mean the work of authorship, whether in Source or
    Object form, made available under the License, as indicated by a
    copyright notice that is included in or attached to the work
    (an example is provided in the Appendix below).

    "Derivative Works" shall mean any work, whether in Source or Object
    form, that is based on (or derived from) the Work and for which the
    editorial revisions, annotations, elaborations, or other modifications
    represent, as a whole, an original work of authorship. For the purposes
    of this License, Derivative Works shall not include works that remain
    separable from, or merely link (or bind by name) to the interfaces of,
    the Work and Derivative Works thereof.

    "Contribution" shall mean any work of authorship, including
    the original version of the Work and any modifications or additions
    to that Work or Derivative Works thereof, that is intentionally
    submitted to Licensor for inclusion in the Work by the copyright owner
    or by an individual or Legal Entity authorized to submit on behalf of
    the copyright owner. For the purposes of this definition, "submitted"
    means any form of electronic, verbal, or written communication sent
    to the Licensor or its representatives, including but not limited to
    communication on electronic mailing lists, source code control systems,
    and issue tracking systems that are managed by, or on behalf of, the
    Licensor for the purpose of discussing and improving the Work, but
    excluding communication that is conspicuously marked or otherwise
    designated in writing by the copyright owner as "Not a Contribution."

    "Contributor" shall mean Licensor and any individual or Legal Entity
    on behalf of whom a Contribution has been received by Licensor and
    subsequently incorporated within the Work.

2.  Grant of Copyright License. Subject to the terms and conditions of
    this License, each Contributor hereby grants to You a perpetual,
    worldwide, non-exclusive, no-charge, royalty-free, irrevocable
    copyright license to reproduce, prepare Derivative Works of,
    publicly display, publicly perform, sublicense, and distribute the
    Work and such Derivative Works in Source or Object form.

3.  Grant of Patent License. Subject to the terms and conditions of
    this License, each Contributor hereby grants to You a perpetual,
    worldwide, non-exclusive, no-charge, royalty-free, irrevocable
    (except as stated in this section) patent license to make, have made,
    use, offer to sell, sell, import, and otherwise transfer the Work,
    where such license applies only to those patent claims licensable
    by such Contributor that are necessarily infringed by their
    Contribution(s) alone or by combination of their Contribution(s)
    with the Work to which such Contribution(s) was submitted. If You
    institute patent litigation against any entity (including a
    cross-claim or counterclaim in a lawsuit) alleging that the Work
    or a Contribution incorporated within the Work constitutes direct
    or contributory patent infringement, then any patent licenses
    granted to You under this License for that Work shall terminate
    as of the date such litigation is filed.

4.  Redistribution. You may reproduce and distribute copies of the
    Work or Derivative Works thereof in any medium, with or without
    modifications, and in Source or Object form, provided that You
    meet the following conditions:

    (a) You must give any other recipients of the Work or
    Derivative Works a copy of this License; and

    (b) You must cause any modified files to carry prominent notices
    stating that You changed the files; and

    (c) You must retain, in the Source form of any Derivative Works
    that You distribute, all copyright, patent, trademark, and
    attribution notices from the Source form of the Work,
    excluding those notices that do not pertain to any part of
    the Derivative Works; and

    (d) If the Work includes a "NOTICE" text file as part of its
    distribution, then any Derivative Works that You distribute must
    include a readable copy of the attribution notices contained
    within such NOTICE file, excluding those notices that do not
    pertain to any part of the Derivative Works, in at least one
    of the following places: within a NOTICE text file distributed
    as part of the Derivative Works; within the Source form or
    documentation, if provided along with the Derivative Works; or,
    within a display generated by the Derivative Works, if and
    wherever such third-party notices normally appear. The contents
    of the NOTICE file are for informational purposes only and
    do not modify the License. You may add Your own attribution
    notices within Derivative Works that You distribute, alongside
    or as an addendum to the NOTICE text from the Work, provided
    that such additional attribution notices cannot be construed
    as modifying the License.

    You may add Your own copyright statement to Your modifications and
    may provide additional or different license terms and conditions
    for use, reproduction, or distribution of Your modifications, or
    for any such Derivative Works as a whole, provided Your use,
    reproduction, and distribution of the Work otherwise complies with
    the conditions stated in this License.

5.  Submission of Contributions. Unless You explicitly state otherwise,
    any Contribution intentionally submitted for inclusion in the Work
    by You to the Licensor shall be under the terms and conditions of
    this License, without any additional terms or conditions.
    Notwithstanding the above, nothing herein shall supersede or modify
    the terms of any separate license agreement you may have executed
    with Licensor regarding such Contributions.

6.  Trademarks. This License does not grant permission to use the trade
    names, trademarks, service marks, or product names of the Licensor,
    except as required for reasonable and customary use in describing the
    origin of the Work and reproducing the content of the NOTICE file.

7.  Disclaimer of Warranty. Unless required by applicable law or
    agreed to in writing, Licensor provides the Work (and each
    Contributor provides its Contributions) on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
    implied, including, without limitation, any warranties or conditions
    of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A
    PARTICULAR PURPOSE. You are solely responsible for determining the
    appropriateness of using or redistributing the Work and assume any
    risks associated with Your exercise of permissions under this License.

8.  Limitation of Liability. In no event and under no legal theory,
    whether in tort (including negligence), contract, or otherwise,
    unless required by applicable law (such as deliberate and grossly
    negligent acts) or agreed to in writing, shall any Contributor be
    liable to You for damages, including any direct, indirect, special,
    incidental, or consequential damages of any character arising as a
    result of this License or out of the use or inability to use the
    Work (including but not limited to damages for loss of goodwill,
    work stoppage, computer failure or malfunction, or any and all
    other commercial damages or losses), even if such Contributor
    has been advised of the possibility of such damages.

9.  Accepting Warranty or Additional Liability. While redistributing
    the Work or Derivative Works thereof, You may choose to offer,
    and charge a fee for, acceptance of support, warranty, indemnity,
    or other liability obligations and/or rights consistent with this
    License. However, in accepting such obligations, You may act only
    on Your own behalf and on Your sole responsibility, not on behalf
    of any other Contributor, and only if You agree to indemnify,
    defend, and hold each Contributor harmless for any liability
    incurred by, or claims asserted against, such Contributor by reason
    of your accepting any such warranty or additional liability.

END OF TERMS AND CONDITIONS

APPENDIX: How to apply the Apache License to your work.

      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "[]"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.

Copyright 2025 Vercel Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
`;

export const FILE_PACKAGE_JSON = `{
  "name": "just-bash",
  "version": "2.7.0",
  "description": "A simulated bash environment with virtual filesystem",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/vercel-labs/just-bash.git"
  },
  "homepage": "https://github.com/vercel-labs/just-bash#readme",
  "type": "module",
  "main": "dist/bundle/index.js",
  "types": "dist/index.d.ts",
  "author": "Malte and Claude",
  "license": "Apache-2.0"
}`;

export const FILE_AGENTS_MD = `# Agent instructions

- use \`pnpm dev:exec\` for evaluating scripts using BashEnv during development. See Debugging info below.
- Install packages via pnpm rather than editing package.json directly
- Bias towards making new test files that are roughly logically grouped rather than letting test files gets too large. Try to stay below 300 lines. Prefer making a new file when you want to add a \`describe()\`
- Prefer asserting the full STDOUT/STDERR output rather than using toContain or not.toContain
- Always also add \`comparison-tests\` for major command functionality, but edge cases should always be covered in unit tests which are mush faster (\`pnpm test:comparison\`)
- When you are unsure about bash/command behavior, create a \`comparison-tests\` test file to ensure compat.
- \`--help\` does not need to pass comparison tests and should reflect actual capability
- Commands must handle unknown arguments correctly
- Always ensure all tests pass in the end and there are no compile and lint errors
- Use \`pnpm lint:fix\`
- Always also run \`pnpm knip\`
- Strongly prefer running a temporary comparison test or unit test over an ad-hoc script to figure out the behavior of some bash script or API.
- The implementation should align with the real behavior of bash, not what is convenient for TS or TE tests.
- Always make sure to build before using dist
- Biome rules often have the same name as eslint rules (if you are lookinf for one)
- Error / show usage on unknown flags in commands and built-ins (unless real bash also ignores)
- Dependencies that use wasm are not allowed (exception: sql.js for SQLite, approved for security sandboxing). Binary npm packages are fine
- When you implement multiple tasks (such as multiple commands or builtins or discovered bugs), so them one at a time, create tests, validate, and then move on
- Running tests does not require building first

## Debugging

- Don't use \`cat > test-direct.ts << 'SCRIPT'\` style test scripts because they constantly require 1-off approval.
- Instead use \`pnpm dev:exec\`
  - use \`--real-bash\` to also get comparison output from the system bash
  - use \`--print-ast\` to also print the AST of the program as parsed by our parser.ts

## Commands

- Must have usage statement
- Must error on unknown options (unless bash ignores them)
- Must have extensive unit tests collocated with the command
- Should have comparison tests if there is doubt about behavior

## Interpreter

- We explicitly don't support 64bit integers
- Must never hang. All parsing and execution should have reasonable max limits to avoid runaway compute.
`;
