import { afterEach, beforeEach, describe, it } from "vitest";
import {
  cleanupTestDir,
  compareOutputs,
  createTestDir,
  setupFiles,
} from "./fixture-runner.js";

describe("jq filtered deletion and paths", () => {
  let testDir: string;
  beforeEach(async () => {
    testDir = await createTestDir();
  });
  afterEach(async () => {
    await cleanupTestDir(testDir);
  });

  it.each([
    ['{"a":3}', "del(.a | numbers)"],
    ['{"a":"keep"}', "del(.a | numbers)"],
    ['{"a":{"b":1}}', "del(.a | objects | .b | numbers)"],
    ...[
      "numbers",
      "strings",
      "booleans",
      "nulls",
      "arrays",
      "objects",
      "iterables",
      "scalars",
      "values",
    ].map((name) => ['[null,false,3,"x",[],{}]', `del(.[] | ${name})`]),
    ['{"i":"y","a":{"i":"x","x":1,"y":2}}', "del(.a[.i])"],
    ['{"i":"y","a":{"i":"x","x":1,"y":2}}', "path(.a[.i])"],
    ['{"i":"y","a":{"i":"x","x":1,"y":2}}', "[.a[.i]]"],
    ['{"arr":["a","b","c"]}', 'del(.arr[] | select(. == "b"))'],
    ['{"arr":["b","a","b","b","c","b"]}', 'del(.arr[] | select(. == "b"))'],
    ['{"arr":["a","b"]}', 'del(.arr[] | select(. == "missing"))'],
    ['{"arr":["b","b"]}', 'del(.arr[] | select(. == "b"))'],
    ['{"arr":[]}', 'del(.arr[] | select(. == "b"))'],
    ['{"arr":["a","b","c"]}', '[path(.arr[] | select(. == "b"))]'],
    ['{"arr":["a","b","c"]}', "[path(.arr[])]"],
    [
      '{"arr":[{"drop":true,"v":1},{"drop":false,"v":2},{"drop":true,"v":3}]}',
      "del(.arr[] | select(.drop) | .v)",
    ],
    [
      '{"arr":[{"drop":true,"v":1},{"drop":false,"v":2}]}',
      "[path(.arr[] | select(.drop) | .v)]",
    ],
    ['{"a":[[1,2,3],[2,2],[3]]}', "del(.a[][] | select(. == 2))"],
    ['{"a":{"x":1,"y":2,"z":2}}', "del(.a[] | select(. == 2))"],
    ['{"a":[{"x":1},{"x":2}]}', "del(.a[].x)"],
    ['{"arr":["a","b","c","d"]}', "del(.arr[0], .arr[2])"],
    ['{"arr":["a","b","c","d"]}', "del(.arr[1], .arr[1], .arr[-3])"],
    ['{"arr":[{"x":1},{"x":2},{"x":3}]}', "del(.arr[0], .arr[1].x)"],
    ['{"arr":[{"x":1},{"x":2}]}', "del(.arr[-1].x)"],
    ['{"arr":[1,2]}', "del(.arr[-99], .arr[99])"],
    ['{"arr":[1,2]}', "del(.arr[])"],
    ['{"arr":[1,2]}', "del(.arr, .arr[0])"],
    ['{"arr":[1,2]}', "del(empty)"],
    ['{"arr":[1,2]}', "del(.)"],
    ['{"arr":[1,2]}', "del(.missing.child)"],
    ['{"arr":[1,2]}', "del(.arr[0,1])"],
    ['{"arr":[1,2]}', "[path(.arr[0,1])]"],
    ['{"arr":null}', "del(.arr[]?)"],
    ['{"arr":[{"x":1},{"x":2}]}', "del(.arr[-1] | .x)"],
    ['{"arr":[1,2]}', "del((.arr[], .arr[]) | select(. == 1))"],
    ['{"arr":[1,2]}', "[path((.arr[], .arr[]) | select(. == 1))]"],
    [
      '{"arr":[1,2]}',
      "[path(.arr[] | select(. == 1)), path(.arr[] | select(. == 9))]",
    ],
    ["[[1],null,[2]]", "del(.[][]?)"],
    ["[[1],null,[2]]", "[path(.[][]?)]"],
    ["[[1],null,[2]]", "del((.[][])?)"],
    ["[[1],null,[2]]", "[path((.[][])?)]"],
    ['[[1],"s",{"a":1}]', "[path(.[][0]?)]"],
    ['[{"x":1},4,{"x":2}]', "try del(.[].x) catch ."],
    ['[{"x":1},4,{"x":2}]', "del(.[].x?)"],
    ['[{"x":1},4,{"x":2}]', "[path(.[].x?)]"],
    ['{"a":1}', "try del(.a.b) catch ."],
    ['{"a":1}', "[path(.a.b?)]"],
    ["1", "try [path(.a.b?)] catch ."],
    ["1", "[path(.a?.b)]"],
    ['{"a":null}', "del(.a.b)"],
    ['{"a":[1]}', 'try del(.a["b"]) catch .'],
    ['{"a":{"b":1}}', "try del(.a[0]) catch ."],
    ['"abcdefghijklmnop"', "try [path(.[])] catch ."],
    ['{"a":3}', "del(.a | tonumber)"],
    ['{"a":"3"}', "try del(.a | tonumber) catch ."],
    ['{"a":"x"}', "del(.a | tostring)"],
    ['{"a":3}', "try del(.a | tostring) catch ."],
    [
      '{"a":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]}',
      "try del(.a | map(.)) catch .",
    ],
    ["[1,2,3]", "del(.[-0.5])"],
    ["[1,2,3]", "del(.[-1.5])"],
    ["[1,2,3]", "del(.[-0.1], .[-3.5])"],
    ["[1,2,3,2]", "del(first(.[] | select(. == 2)))"],
    ["[1,2]", '[path(first(.[0], error("x")))]'],
    ["[1,2]", 'try [path(first(error("x")))] catch .'],
    ["[1,2,3]", "del(limit(2; .[]))"],
    ["[1,[2]]", "del(nth(1; .[]))"],
    ["[1,2,3]", "try [path(nth(nan; .[]))] catch ."],
    ["[1,2,3]", "[path(limit(1,2; .[]))]"],
    ["[1,2,3]", '[path(limit(2; .[0], .[1], error("x")))]'],
    ["[[1],[2,3]]", "[path(nth(1; .[][]))]"],
    ["[[1],[2,3]]", "[path(nth(5; .[][]))]"],
    ["[[1],[2,3]]", "[path(nth(1.5; .[][]))]"],
    ["[[1],[2,3]]", "[path(limit(1.5; .[][]))]"],
    ["[1,2]", "[path(first(recurse(.)))]"],
    ["[1,2]", "[path(limit(2; recurse(.)))]"],
    ["[1,2]", "[path(nth(1; .[], recurse(.)))]"],
    ["[[1],[2,3]]", "[path(first(recurse(.) | .[0]))]"],
    ["[1,[2,[3,2]]]", "del(first(recurse(.[]?) | select(. == 2)))"],
    ['{"a":1,"b":2}', "del(if .a then .a else .b end)"],
    ['{"a":1,"b":2}', "[path(if .c then .a end)]"],
    ['{"a":1,"b":2}', "[path(if .c then .a elif .b then .b else . end)]"],
    ['{"a":1,"b":2}', "[path(if (true,false) then .a else .b end)]"],
    ['{"a":1,"b":2}', "try del(if .a then 1 else .b end) catch ."],
    [
      '{"a":1,"b":2,"c":3}',
      "del(if false then .a elif empty then .b else .c end)",
    ],
    [
      '{"a":1,"b":2,"c":3}',
      "del(if false then . elif (true,false) then .a else .b end)",
    ],
    [
      '{"a":1,"b":2,"c":3}',
      "[path(if false then .a elif false then .b elif (true,false) then .c end)]",
    ],
    [
      '{"a":1,"b":2,"c":3}',
      "[if false then .a elif (true,false) then .b else .c end]",
    ],
    [
      '{"a":1,"b":2,"c":3}',
      "[if false then .a elif empty then .b else .c end]",
    ],
    ['{"a":1,"b":2}', "del(.c // .b)"],
    ['{"a":[null,1,false,2]}', "[path(.a[] // .b)]"],
    ['{"a":[null,false]}', "[path(.a[] // .b)]"],
    ['{"a":1}', "[path(.c // empty)]"],
    ['{"a":{"b":1}}', 'del(getpath(["a","b"]))'],
    ["{}", '[path(getpath(["a","b"], ["c"]))]'],
    ['{"a":1}', 'try del(getpath(["a","b"])) catch .'],
    ['{"a":1}', 'try del(getpath("a")) catch .'],
    ['{"a":"abc"}', 'del(.a | ltrimstr("z"))'],
    ['{"a":"abc"}', 'try del(.a | ltrimstr("z","a")) catch .'],
    ['{"a":"abc"}', '[path(.a | ltrimstr("z","y"))]'],
    ['{"a":"abc"}', 'try del(.a | ltrimstr("a")) catch .'],
    ['{"a":"abc"}', 'try del(.a | ltrimstr("")) catch .'],
    ['{"a":"abc"}', 'del(.a | rtrimstr("z"))'],
    ['{"a":"abc"}', 'try del(.a | rtrimstr("c")) catch .'],
    ['{"a":3}', 'del(.a | ltrimstr("a"))'],
    ['{"a":1,"b":2}', "del(.a as $x | .b)"],
    ['{"a":[1,2],"b":2}', "[path(.a[] as $x | .b)]"],
    ['{"a":[1]}', 'try del(.a as [$x] | .a) catch "rejected"'],
    ['{"a":1}', "[path(label $f | .a, break $f, .b)]"],
    ['{"a":1}', "del(try .a)"],
    ['{"a":1}', "del(label $f | .a)"],
    ['{"a":3}', "try del(.a | . + 0) catch ."],
    ['{"a":3}', "try del(.a | length) catch ."],
    [
      '{"a":[1,"s",2]}',
      '[path(.a[] | try (if type == "string" then error else . end))]',
    ],
    ['{"a":1}', 'try del(try error("x") catch .) catch .'],
    ['{"a":1}', 'del(try error("x") catch empty)'],
    ["[1,[2,[3]]]", "del(recurse | numbers)"],
    ["[1,[null]]", "[path(recurse(.[]?))]"],
    ['{"a":{"a":1}}', "[path(recurse(.a; . != 1))]"],
    ['{"a":{"a":null}}', "[path(recurse(.a; . != null and (true,true)))]"],
    ["[1,[2]]", "try [path(recurse(.[]))] catch ."],
  ])("%s | %s", async (input, filter) => {
    const env = await setupFiles(testDir, { "input.json": input });
    await compareOutputs(env, testDir, `jq -c '${filter}' input.json`);
  });
});
