name: Comparison Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  comparison-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run comparison tests
        run: pnpm test:comparison

      - name: Run comparison tests in record mode
        run: pnpm test:comparison:record

      - name: diff
        run: git diff

      # Fail if there are any diffs
      - name: Fail if there are any diffs
        run: if [ -n "$(git diff --name-only)" ]; then exit 1; fi
